[colors]
background = #282828
foreground = #dfddc8
primary = #a9b665
accent = #d8a657
alert = #ea6962
disabled = #504945

[bar/main]
width = 100%
height = 22pt
radius = 0
bottom = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
border-size = 0px
padding-left = 2
padding-right = 2
module-margin = 1

separator = " "
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:size=10;2"

# Раскладываем модули по местам
modules-left = bspwm
modules-center = date
modules-right = xkeyboard backlight pulseaudio battery network

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/bspwm]
type = internal/bspwm
label-focused = %name%
label-focused-background = ${colors.disabled}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = caps lock
format = <label-layout>
format-prefix = "    "
format-prefix-foreground = ${colors.accent}
label-layout = %layout%
label-layout-transform = uppercase

[module/backlight]
type = internal/backlight
card = amdgpu_bl0
format = <label>
format-prefix = "    "
format-prefix-foreground = ${colors.accent}
label = %percentage%%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume =     %percentage%%
label-volume-foreground = ${colors.primary}
label-muted =     muted
label-muted-foreground = ${colors.disabled}

[module/battery]
type = internal/battery
full-at = 99
low-at = 15
battery = BAT0
adapter = ADP1
poll-interval = 2

format-charging = <label-charging>
label-charging =    %percentage%%
label-charging-foreground = ${colors.primary}

format-discharging = <label-discharging>
label-discharging =    %percentage%%
label-discharging-foreground = ${colors.foreground}

format-low = <label-low>
label-low =    %percentage%%
label-low-foreground = ${colors.alert}

[module/date]
type = internal/date
interval = 1
# ДОБАВЛЕНО: Формат времени с секундами и подробной датой
date = "%H:%M:%S"
date-alt = "%A, %d %B %Y"
label = %date%
label-foreground = ${colors.foreground}

[module/network]
type = internal/network
interface-type = wireless
interval = 3
label-connected =    %essid%
label-connected-foreground = ${colors.primary}
label-disconnected =     down
label-disconnected-foreground = ${colors.disabled}
