#!/bin/sh

# 1. АВТОЗАПУСК ПРОГРАММ
waybar &
swww init &
dunst &

# 2. МОДИФИКАТОР (Кнопка Super/Logo)
MOD="Logo"

# 3. ГОРЯЧИЕ КЛАВИШИ ЗАПУСКА ПРОГРАММ
river map normal $MOD Return spawn alacritty       # Super + Enter = Твой Alacritty
river map normal $MOD B spawn zen                 # Super + B = Zen Browser
river map normal $MOD E spawn thunar              # Super + E = Проводник Thunar
river map normal $MOD R spawn "rofi -show drun"    # Super + R = Меню запуска Rofi

# 4. УПРАВЛЕНИЕ ОКНАМИ И СЕССИЕЙ
river map normal $MOD Q close                     # Super + Q = Закрыть окно
river map normal $MOD Space toggle-float          # Super + Пробел = Переключить в плавающий режим
river map normal $MOD F toggle-fullscreen         # Super + F = Полный экран

# Перемещение фокуса между окнами (Super + J / K)
river map normal $MOD J focus-view next
river map normal $MOD K focus-view previous

# Перенос окон на другие теги (Рабочие столы 1-9)
for i in $(seq 1 9); do
    tags=$((1 << (i - 1)))
    river map normal $MOD $i set-focused-tags $tags
    river map normal $MOD+Shift $i set-view-tags $tags
done

# Выход из River (Super + Shift + E)
river map normal $MOD+Shift E exit

# 5. СТИЛЬ ГРАНИЦ ОКON
river border-width 2
river border-color-focused "0xff5e81ac"           # Nord Blue
river border-color-unfocused "0xff4c566a"         # Серый

# 6. ЗАПУСК КОМПОНОВЩИКА ОКON (Обязательно для тайлинга)
river default-layout rivertile
exec rivertile -view-padding 5 -outer-padding 5

