#!/bin/sh

setxkbmap -layout "us,ru" -option "grp:caps_toggle,grp_led:scroll"

pkill -9 -x sxhkd
pkill -9 -x picom
pkill -9 -x polybar
pkill -9 -x dunst

sxhkd &
picom --config ~/.config/picom/picom.conf -b &
polybar left &
polybar center &
polybar right &
dunst &

if [ -f "$HOME/.current_wallpaper" ]; then
    feh --bg-fill "$(cat "$HOME/.current_wallpaper")"
else
    feh --bg-fill "$HOME/Pictures/Wallpapers/flower-1.jpg" 2>/dev/null || feh --bg-color "#282828"
fi

bspc monitor -d 1 2 3 4 5
bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#a9b665"  
bspc config normal_border_color  "#504945"  
bspc config split_ratio          0.52

# УМНЫЕ ПРАВИЛА ЦЕНТРИРОВАНИЯ ОКН
bspc config focus_by_shift               true
bspc config history_aware_focus          true
bspc config center_pseudo_tiled          true
bspc rule -a Rofi state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Lxappearance state=floating center=true
