#!/bin/sh

# Настройка раскладки: Английская и Русская, переключение по CapsLock
setxkbmap -layout "us,ru" -option "grp:caps_toggle,grp_led:scroll"

# Автозапуск экосистемы Gruvbox
picom --config ~/.config/picom/picom.conf -b &
polybar main &  # ИСПРАВЛЕНО: Запуск панели Polybar с именем "main"
dunst &

# Рабочие столы
bspc monitor -d 1 2 3 4 5

# Настройки окон в стиле Gruvbox Material
bspc config border_width         3
bspc config window_gap          14

# Цвета Gruvbox
bspc config focused_border_color "#a9b665"
bspc config normal_border_color  "#504945"
